import { useMemo } from "react";
import { useWorkspace } from "../../state/WorkspaceContext";
import { fmt, fmtInt } from "../../utils/workspace";
import { openSurveyFilePicker } from "../modals/WorkspaceModals";

const GIS_TOOLS = [
  ["pan", "✋", "Pan / geser peta"], ["select", "◇", "Select segment"], ["box", "⛶", "Box Select"], ["sep"], ["vertex", "●", "Edit Vertex"], ["addVertex", "＋•", "Tambah Vertex"], ["removeVertex", "−•", "Hapus Vertex"], ["redraw", "✎", "Redraw Boundary"], ["split", "◫", "Split Segment"], ["merge", "⊕", "Merge Adjacent"], ["exclude", "×", "Keluarkan dari Draft"], ["sep2"], ["measure", "↔", "Ukur jarak"], ["fitSelection", "◎", "Fit Selection"], ["fitDraft", "⌗", "Fit Draft"], ["tilt", "◩", "Tilt map"], ["sep3"], ["undo", "↶", "Undo"], ["redo", "↷", "Redo"], ["reset", "⟲", "Reset selected geometry"], ["sep4"], ["compare", "⇄", "Compare Draft"], ["zoomIn", "＋", "Perbesar"], ["zoomOut", "−", "Perkecil"],
];

const CATALOG = [
  ["speed_corridor", "Speed Corridor", "Polygon", "Review Draft → Active", true],
  ["haul_road", "Haul Road", "LineString + corridor", "Draft → Published", true],
  ["pit_stop_area", "Pit Stop Area", "Polygon", "Draft → Published", true],
  ["district_boundary", "District Boundary", "Polygon", "Reference", false],
  ["loader_estimate", "Loader Estimate", "Polygon", "Derived", false],
];

export default function GisWorkspace({ mapRef }) {
  const { state, dispatch } = useWorkspace();
  if (state.mode !== "gis") return null;
  const segments = state.speed.draft?.segments ?? state.speed.active?.segments ?? [];
  const selected = new Set(state.gis.selectedSegments);
  const filtered = segments.filter((segment) => !state.gis.search || `${segment.id} ${segment.roadName} ${segment.routeLabel}`.toLowerCase().includes(state.gis.search.toLowerCase()));
  const grouped = useMemo(() => {
    const map = new Map(); filtered.forEach((segment) => { if (!map.has(segment.routeId)) map.set(segment.routeId, []); map.get(segment.routeId).push(segment); }); return [...map.entries()];
  }, [filtered]);
  const primary = segments.find((segment) => selected.has(segment.id));
  const select = (segmentId, multi = false) => {
    const next = new Set(multi ? selected : []); next.has(segmentId) ? next.delete(segmentId) : next.add(segmentId); dispatch({ type: "PATCH_GIS", patch: { selectedSegments: [...next], inspectorOpen: true } }); dispatch({ type: "PATCH_SPEED", patch: { selectedSegments: [...next] } });
  };
  const useTool = (tool) => {
    if (tool === "compare") return dispatch({ type: "PATCH_GIS", patch: { compareOpen: !state.gis.compareOpen } });
    if (tool === "zoomIn") return mapRef.current?.zoomIn(); if (tool === "zoomOut") return mapRef.current?.zoomOut(); if (tool === "fitDraft") return mapRef.current?.fitSegments();
    if (tool === "tilt") { const next = state.tilt === 0 ? 45 : state.tilt === 45 ? 60 : 0; dispatch({ type: "SET_TILT", value: next }); return; }
    if (["undo","redo"].includes(tool)) return;
    dispatch({ type: "PATCH_GIS", patch: { tool, dirty: ["vertex","addVertex","removeVertex","redraw","split","merge","exclude","reset"].includes(tool) ? true : state.gis.dirty } });
  };
  return (
    <div id="speedGisHandoffModal" className="speed-modal-backdrop gis-workspace-backdrop gis-tab-workspace" role="region" aria-label="GIS Workspace">
      <section className="speed-modal gis-workspace-shell">
        <header className="gis-command-bar">
          <button className="btn" type="button" onClick={() => dispatch({ type: "SET_MODE", mode: state.speed.draft || state.speed.active ? "speed" : "cycle" })}>← {state.speed.draft || state.speed.active ? "Speed Analysis" : "Analysis"}</button>
          <div className="gis-command-title"><span className={`gis-dirty-dot ${state.gis.dirty ? "" : "clean"}`}></span><div><strong>GIS Workspace · Speed Segment Geometry</strong><span>Shared map · geometry tersimpan kembali ke Review Draft</span></div></div>
          <div className="gis-map-tools" aria-label="GIS tools">{GIS_TOOLS.map(([tool, icon, title]) => tool.startsWith("sep") ? <span key={tool} className="tool-sep"/> : <button key={tool} className={`toolbtn ${state.gis.tool===tool?'active':''}`} type="button" title={title} disabled={tool==='undo'&&!state.gis.undo.length||tool==='redo'&&!state.gis.redo.length} onClick={()=>useTool(tool)}>{icon}</button>)}</div>
          <div className="gis-command-actions"><button className="btn survey-import-btn-v23" type="button" onClick={openSurveyFilePicker}>＋ Impor Pembanding</button><button className="btn" type="button" onClick={()=>dispatch({type:'PATCH_GIS',patch:{compareOpen:!state.gis.compareOpen}})}>Compare Draft</button><button className="btn primary" type="button" disabled={!state.gis.dirty} onClick={()=>dispatch({type:'PATCH_GIS',patch:{dirty:false}})}>Save to Draft</button></div>
        </header>
        <aside className="gis-workspace-sidebar" aria-label="Layer GIS">
          <div className="gis-sidebar-head"><strong>Layers</strong><span>Draft, route, dan seluruh segment</span><input className="gis-tree-search" type="search" placeholder="Cari Segment ID atau Road Name…" value={state.gis.search} onChange={(event)=>dispatch({type:'PATCH_GIS',patch:{search:event.target.value}})}/></div>
          <div className="gis-layer-scroll">
            <section className="gis-catalog-v22"><div className="gis-catalog-head-v22"><strong>Layer Geometry</strong><small>shared catalog</small></div>{CATALOG.map(([key,label,geometry,lifecycle,editable])=><button className={`gis-catalog-row-v22 ${state.gis.catalogLayer===key?'active':''}`} type="button" key={key} onClick={()=>dispatch({type:'PATCH_GIS',patch:{catalogLayer:key}})}><i className={`gis-catalog-symbol-v22 ${key}`}></i><span><strong>{label}</strong><small>{geometry} · {lifecycle}</small></span><b>{editable?'Edit':'Read'}</b></button>)}</section>
            <section className="gis-layer-tree" aria-label="Hierarchy Review Draft"><div className="gis-tree-root"><strong>{state.speed.draft?.version ?? state.speed.active?.version ?? "Review Draft"}</strong><span className="gis-tree-count">{segments.length}</span></div><div className="gis-tree-routes">{grouped.length ? grouped.map(([routeId,items])=><div key={routeId}><button className="gis-tree-route" type="button"><span className="gis-tree-caret">▾</span><span className="gis-tree-route-name">{items[0]?.routeLabel ?? routeId}</span><span className="gis-tree-route-meta">{items.length} segment</span></button><div className="gis-tree-children">{items.map((segment)=><div className={`gis-tree-segment ${selected.has(segment.id)?'selected':''}`} key={segment.id} onClick={(event)=>select(segment.id,event.ctrlKey||event.metaKey)}><span className="gis-tree-branch"></span><i className={`gis-tree-status ${segment.reviewed?'':'review'}`}></i><span className="gis-tree-segment-label"><strong>{segment.id}</strong><span>{segment.roadName||'Belum dinamai'} · {segment.sta}</span></span><button className="gis-tree-segment-action" type="button">⋯</button></div>)}</div></div>) : <div className="gis-tree-empty">Generate Speed Draft untuk menampilkan hierarchy segment.</div>}</div></section>
            <section className="gis-layer-group survey-compare-group-v23"><div className="gis-layer-group-head"><strong>Perbandingan Jalur</strong><small>{state.survey.coordinates.length?`${fmtInt(state.survey.coordinates.length)} titik`:'filter aktif'}</small></div><label className="gis-layer-row-v18 survey-layer-row-v23"><input type="checkbox" checked={state.gis.layers.trace} onChange={(event)=>dispatch({type:'PATCH_GIS',patch:{layers:{...state.gis.layers,trace:event.target.checked}}})}/><i className="gis-layer-symbol survey-symbol-device-v23"></i><span className="gis-layer-name">Jejak Unit</span><span></span></label><label className="gis-layer-row-v18 survey-layer-row-v23"><input type="checkbox" disabled={!state.survey.coordinates.length} checked={state.survey.visible&&!!state.survey.coordinates.length} onChange={(event)=>dispatch({type:'PATCH_SURVEY',patch:{visible:event.target.checked}})}/><i className="gis-layer-symbol survey-symbol-reference-v23"></i><span className="gis-layer-name">{state.survey.fileName||'Data survei belum diimpor'}</span><button className={`survey-layer-action-v23 ${state.survey.coordinates.length?'remove':''}`} type="button" onClick={(event)=>{event.preventDefault();state.survey.coordinates.length?dispatch({type:'PATCH_SURVEY',patch:{coordinates:[],fileName:'',headers:[],rows:[],roles:[]}}):openSurveyFilePicker()}}>{state.survey.coordinates.length?'Hapus':'Impor'}</button></label></section>
            <section className="gis-layer-group"><div className="gis-layer-group-head"><strong>Data Pendukung</strong><small>read-only</small></div>{[['loading','PLM Loading','loading'],['loader','Estimasi Loader Area','valid']].map(([key,label,symbol])=><label className="gis-layer-row-v18" key={key}><input type="checkbox" checked={state.gis.layers[key]} onChange={(event)=>dispatch({type:'PATCH_GIS',patch:{layers:{...state.gis.layers,[key]:event.target.checked}}})}/><i className={`gis-layer-symbol ${symbol}`}></i><span className="gis-layer-name">{label}</span></label>)}</section>
            <section className="gis-layer-group"><div className="gis-layer-group-head"><strong>Peta Dasar</strong><small>read-only</small></div>{[['roads','Jalan Tambang','road'],['boundary','Boundary Distrik','boundary'],['ortho','Orthophoto','ortho']].map(([key,label,symbol])=><label className="gis-layer-row-v18" key={key}><input type="checkbox" checked={state.gis.layers[key]} onChange={(event)=>dispatch({type:'PATCH_GIS',patch:{layers:{...state.gis.layers,[key]:event.target.checked}}})}/><i className={`gis-layer-symbol ${symbol}`}></i><span className="gis-layer-name">{label}</span></label>)}</section>
          </div>
          <div className="gis-sidebar-context"><div><span>Dataset</span><strong>Speed Segments</strong></div><div><span>Draft</span><strong>{state.speed.draft?.version??state.speed.active?.version??'—'}</strong></div><div><span>Selection</span><strong>{selected.size} segment</strong></div><div><span>Sumber</span><strong>Auto Suggest + telemetry</strong></div></div>
        </aside>
        {state.gis.inspectorOpen && primary && <aside className="gis-workspace-inspector"><div className="gis-inspector-head"><div><strong>{primary.id}</strong><span>Geometry dan evidence</span></div><button className="speed-modal-x" type="button" onClick={()=>dispatch({type:'PATCH_GIS',patch:{inspectorOpen:false}})}>×</button></div><div className="gis-inspector-body"><div className={`gis-inspector-status ${primary.reviewed?'valid':''}`}>{primary.reviewed?'Reviewed':'Perlu Review'}</div><div className="gis-inspector-kv"><span>Road Name</span><strong>{primary.roadName||'—'}</strong><span>Route</span><strong>{primary.routeLabel}</strong><span>Panjang</span><strong>{fmtInt(primary.lengthM)} m</strong><span>Actual Speed</span><strong>{fmt(primary.avgActual,1)} km/h</strong><span>Unit Evidence</span><strong>{primary.unitNos.length}</strong><span>Geometry</span><strong>{primary.polygon.length-1} vertex</strong></div><div className="gis-evidence-list"><strong>Selected Geometry</strong><div>{[...selected].map((id)=><span key={id}>{id}</span>)}</div></div><div className="gis-inspector-actions"><button className="btn primary" type="button" onClick={()=>dispatch({type:'PATCH_GIS',patch:{tool:'vertex',dirty:true}})}>Edit Geometry</button><button className="btn" type="button" onClick={()=>mapRef.current?.fitSegments()}>Fit Segment</button><button className="btn" type="button" onClick={()=>dispatch({type:'UPDATE_SPEED_SEGMENTS',patch:()=>({reviewed:true,status:'Reviewed'})})}>Mark Reviewed</button><button className="btn" type="button" onClick={()=>dispatch({type:'REMOVE_SPEED_SEGMENTS'})}>Keluarkan</button></div></div></aside>}
        {state.gis.compareOpen && <section className="gis-compare-panel"><div className="gis-compare-head"><div><strong>Compare Draft</strong><span>Bandingkan hasil Auto Suggest antar-Draft</span><div className="gis-compare-selects"><select><option>ACTIVE v1</option></select><span>vs</span><select><option>{state.speed.draft?.version??'Current Draft'}</option></select></div></div><button className="speed-modal-x" type="button" onClick={()=>dispatch({type:'PATCH_GIS',patch:{compareOpen:false}})}>×</button></div><div className="gis-compare-summary">{[['Unchanged',Math.max(0,segments.length-3)],['Modified',2],['Added',1],['Removed',0],['Review',segments.filter((s)=>!s.reviewed).length]].map(([label,value])=><button className="gis-compare-stat" type="button" key={label}><strong>{value}</strong><span>{label}</span></button>)}</div><div className="gis-compare-empty">Pilih kategori perubahan untuk fokus geometry pada shared map.</div></section>}
        <div className="gis-status-bar"><span className={`gis-status-dot ${state.gis.dirty?'review':''}`}></span><strong>{state.gis.dirty?'Unsaved geometry changes':'Ready'}</strong><span>{selected.size} segment dipilih</span><span className="spacer"></span><span>WGS84</span><span>z13.0</span></div>
      </section>
      {state.survey.visible&&state.survey.coordinates.length>0&&<div className="survey-map-badge-v23"><span><i className="device"></i>Jejak Unit</span><span><i className="survey"></i>Data Survei</span><strong>{state.survey.fileName}</strong></div>}
    </div>
  );
}
