import { useMemo } from "react";
import { useWorkspace } from "../../state/WorkspaceContext";
import { fmt } from "../../utils/workspace";

const COLUMNS = [
  ["timestampiso", "Timestamp"], ["district", "District"], ["unitno", "Unit No"], ["unittype", "Unit Type"], ["deviceid", "Device ID"], ["gpslat", "GPS Lat"], ["gpslong", "GPS Long"], ["gpsspeed", "GPS Speed"], ["plmstatus", "PLM Status"], ["statusname", "Status Name"],
];

export default function DataLogWorkspace() {
  const { state, dispatch, datalogRows } = useWorkspace();
  if (state.mode !== "datalog") return null;
  const units = state.fixture?.unitNos ?? [];
  const filteredRows = useMemo(() => {
    const query = state.datalog.query.trim().toLowerCase();
    const source = state.datalog.loaded ? state.datalog.rows : [];
    return query ? source.filter((row) => Object.values(row).some((value) => String(value ?? "").toLowerCase().includes(query))) : source;
  }, [state.datalog.rows, state.datalog.query, state.datalog.loaded]);
  const visibleColumns = COLUMNS.filter(([key, label]) => state.datalog.visibleColumns.includes(key) && (!state.datalog.columnSearch || `${key} ${label}`.toLowerCase().includes(state.datalog.columnSearch.toLowerCase())));
  const load = () => dispatch({ type: "PATCH_DATALOG", patch: { loaded: true, rows: datalogRows } });
  const selectUnit = (unitNo) => { const next = new Set(state.datalog.selectedUnits); next.has(unitNo) ? next.delete(unitNo) : next.add(unitNo); dispatch({ type: "PATCH_DATALOG", patch: { selectedUnits: [...next], loaded: false, rows: [] } }); };
  const chartRows = filteredRows.slice(0, 500); const max = Math.max(1, ...chartRows.map((row) => Number(row[state.datalog.chartMetric]) || 0));
  const path = chartRows.map((row, index) => `${index ? "L" : "M"}${54 + 928 * index / Math.max(1, chartRows.length - 1)},${20 + 304 * (1 - (Number(row[state.datalog.chartMetric]) || 0) / max)}`).join(" ");
  return (
    <section className="datalog-workspace-v20" aria-label="Data Log Record Workspace">
      <header className="datalog-topbar-v20"><div className="datalog-title-v20"><strong>Data Log Record</strong><span>Raw telemetry · filter V3 aktif</span></div><input type="search" placeholder="Cari pada data yang dimuat…" value={state.datalog.query} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{query:event.target.value}})}/><div className="datalog-view-tabs-v20">{['table','chart','map'].map((view)=><button className={state.datalog.view===view?'active':''} key={view} type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{view}})}>{view[0].toUpperCase()+view.slice(1)}</button>)}</div><button className="btn" type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{columnPanel:!state.datalog.columnPanel}})}>Columns</button><button className="btn primary" type="button" onClick={load}>Muat data</button><span className="datalog-rows-meta-v20">{state.datalog.loaded ? `${filteredRows.length.toLocaleString('id-ID')} baris · sample prototype` : 'Belum dimuat'}</span></header>
      <aside className="datalog-tree-v20"><div className="datalog-tree-head-v20"><strong>Units</strong><input type="search" placeholder="Cari unit…" value={state.datalog.treeSearch} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{treeSearch:event.target.value}})}/></div><div className="datalog-scope-v21"><label>Group by <select value={state.datalog.groupBy} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{groupBy:event.target.value}})}><option value="unitType">Unit Type</option><option value="loader">Loader</option><option value="availability">Availability</option></select></label><button type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{selectedUnits:state.appliedFilters.units,loaded:false,rows:[]}})}>Reset unit</button><span className="datalog-scope-meta-v21">{state.datalog.selectedUnits.length}/{state.appliedFilters.units.length} unit selected</span></div><div className="datalog-tree-body-v20"><button className="datalog-tree-node-v20 root" type="button"><span className="caret">▾</span><strong className="name">BRCB</strong><span className="meta">{units.length}</span></button><button className="datalog-tree-node-v20 type" type="button"><span className="caret">▾</span><span className="name">DT</span><span className="meta">{state.datalog.selectedUnits.length}/{units.length}</span></button>{units.filter((unit)=>unit.toLowerCase().includes(state.datalog.treeSearch.toLowerCase())).map((unit)=><button className={`datalog-tree-node-v20 unit ${state.datalog.selectedUnits.includes(unit)?'selected':''}`} type="button" key={unit} onClick={()=>selectUnit(unit)}><span className="caret">{state.datalog.selectedUnits.includes(unit)?'✓':'○'}</span><span className="name">{unit}</span><span className="meta available">available</span></button>)}</div></aside>
      <section className={`datalog-stage-v20 ${state.datalog.view==='map'?'map-view':'table-view'}`}>
        {state.datalog.view==='table' && <div className="datalog-table-view-v20">{!state.datalog.loaded?<div className="datalog-empty-v20">Pilih unit lalu tekan <strong>Muat data</strong>.</div>:!filteredRows.length?<div className="datalog-empty-v20">Tidak ada data pada filter aktif.</div>:<table className="datalog-table-v20"><thead><tr><th>No.</th>{visibleColumns.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{filteredRows.slice(0,2500).map((row,index)=><tr key={`${row.timestampms}-${row.unitno}-${index}`}><td>{index+1}</td>{visibleColumns.map(([key])=><td key={key}>{key==='timestampiso'?new Date(row.timestampms+8*3600000).toISOString().slice(8,19).replace('T',' '):typeof row[key]==='number'?fmt(row[key],key.includes('lat')||key.includes('long')?6:2):String(row[key]??'—')}</td>)}</tr>)}</tbody></table>}</div>}
        {state.datalog.view==='chart' && <div className="datalog-chart-view-v20"><div className="datalog-chart-config-v20"><label>X-axis<select><option>Timestamp</option></select></label><label>Metric<select value={state.datalog.chartMetric} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{chartMetric:event.target.value}})}><option value="gpsspeed">GPS Speed</option><option value="gpslat">GPS Lat</option><option value="gpslong">GPS Long</option><option value="plmstatus">PLM Status</option></select></label></div><div className="datalog-chart-canvas-v20"><svg viewBox="0 0 1000 360" preserveAspectRatio="none">{[0,.25,.5,.75,1].map((f)=><line key={f} x1="54" y1={20+304*f} x2="982" y2={20+304*f} stroke="#e7eaee"/>)}<path d={path} fill="none" stroke="#287c94" strokeWidth="3"/></svg><div><span><b>{state.datalog.chartMetric}</b> · {chartRows.length} sample</span></div></div></div>}
        {state.datalog.view==='map' && <div className="datalog-map-view-v20"><aside className="datalog-map-config-v20"><strong>Field mapping</strong><label>Latitude<select value="gpslat"><option>GPS Lat</option></select></label><label>Longitude<select value="gpslong"><option>GPS Long</option></select></label><label>Speed color<select value="gpsspeed"><option>GPS Speed</option></select></label><label className="check"><input type="checkbox" checked={state.datalog.mapFields.dotTrace} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{mapFields:{...state.datalog.mapFields,dotTrace:event.target.checked}}})}/> Dot trace</label></aside></div>}
      </section>
      {state.datalog.columnPanel && <aside className="datalog-columns-panel-v20"><header><strong>Columns</strong><button type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{columnPanel:false}})}>×</button></header><div className="datalog-column-search-v21"><input type="search" placeholder="Cari nama atau key field…" value={state.datalog.columnSearch} onChange={(event)=>dispatch({type:'PATCH_DATALOG',patch:{columnSearch:event.target.value}})}/></div><div>{COLUMNS.filter(([key,label])=>!state.datalog.columnSearch||`${key} ${label}`.toLowerCase().includes(state.datalog.columnSearch.toLowerCase())).map(([key,label])=><label className="datalog-column-row-v20" key={key}><input type="checkbox" checked={state.datalog.visibleColumns.includes(key)} disabled={['timestampiso','district','unitno'].includes(key)} onChange={(event)=>{const next=new Set(state.datalog.visibleColumns);event.target.checked?next.add(key):next.delete(key);dispatch({type:'PATCH_DATALOG',patch:{visibleColumns:[...next]}})}}/><span>{label}{['timestampiso','district','unitno'].includes(key)?' · fixed':''}</span></label>)}</div><footer className="datalog-column-actions-v21"><button type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{visibleColumns:COLUMNS.map(([key])=>key)}})}>Select all</button><button type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{visibleColumns:['timestampiso','district','unitno']}})}>Kosongkan</button><button type="button" onClick={()=>dispatch({type:'PATCH_DATALOG',patch:{columnPanel:false}})}>Selesai</button></footer></aside>}
    </section>
  );
}
