import { useEffect, useMemo, useRef, useState } from "react";
import MapCanvas from "./MapCanvas";
import AnalysisDock from "../dock/AnalysisDock";
import DurationWorkspace from "../modes/DurationWorkspace";
import DataLogWorkspace from "../modes/DataLogWorkspace";
import GisWorkspace from "../modes/GisWorkspace";
import { useWorkspace } from "../../state/WorkspaceContext";
import { fmt, fmtInt } from "../../utils/workspace";

function CycleRibbon() {
  const { state, kpis } = useWorkspace();
  if (state.mode !== "cycle" || state.playback.active) return null;
  const total = Number.isFinite(kpis.cycle) ? kpis.cycle : 0;
  const phases = [
    ["Loading", .16, "var(--series2)"], ["Running muatan", .31, "var(--series3)"], ["Stop muatan", .08, "var(--series6)"], ["Dumping", .12, "var(--series4)"], ["Running kosongan", .33, "var(--series5)"],
  ];
  return <div id="cycleAnalysisRibbon" className="cycle-analysis-ribbon"><div className="cycle-ribbon-head"><div className="cycle-ribbon-title-wrap"><span className="cycle-ribbon-title">Komposisi Cycle</span><span className="cycle-ribbon-value">{total ? `${fmt(total,1)} min` : '—'}</span><span className="cycle-ribbon-meta">teramati per unit</span></div></div><div className="cycle-stack cycle-ribbon-stack">{phases.map(([label,pct,color])=><span key={label} style={{width:`${pct*100}%`,background:color}}></span>)}</div><div className="cycle-ribbon-legend">{phases.map(([label,pct,color])=><div className="cycle-ribbon-item" key={label}><span className="cycle-mini-label"><i className="cycle-mini-dot" style={{background:color}}></i>{label}</span><strong className="cycle-ribbon-time">{total?`${fmt(total*pct,1)} min`:'—'}</strong><span className="cycle-ribbon-pct">{Math.round(pct*100)}%</span></div>)}</div></div>;
}

function SpeedRibbon() {
  const { state, dispatch } = useWorkspace();
  if (state.mode !== "speed" || state.playback.active) return null;
  const draft = state.speed.draft; const active = state.speed.active; const segments = draft?.segments ?? active?.segments ?? []; const reviewed = segments.filter((segment)=>segment.reviewed).length; const gaps = segments.filter((segment)=>segment.samples<3).length; const review = segments.length-reviewed;
  return <div id="speedAnalysisRibbon" className="speed-analysis-ribbon"><div className="speed-ribbon-brand"><div><span className="speed-ribbon-title">Speed Analysis</span><strong>{draft?.version ?? active?.version ?? 'Belum ada Segment Layer'}</strong></div><span className="speed-review-summary">{segments.length?`${segments.length} Segments · ${reviewed} Reviewed · ${review} Suggested`:'Generate Draft dari telemetry aktif'}</span></div><button className="speed-draft-health" type="button" disabled={!segments.length} onClick={()=>dispatch({type:'PATCH_SPEED',patch:{draftHealthOpen:!state.speed.draftHealthOpen}})}><span>Coverage {segments.length?`${Math.max(0,100-gaps*4)}%`:'—'}</span><i></i><span>Gaps {segments.length?gaps:'—'}</span><i></i><span>Review {segments.length?review:'—'}</span><b>⌄</b></button><div className="speed-ribbon-actions"><button className="btn speed-ribbon-btn" type="button" onClick={()=>dispatch({type:'PATCH_SPEED',patch:{modal:'suggest'}})}>Auto Suggest</button><button className="btn primary speed-ribbon-btn" type="button" disabled={!draft&&!active} onClick={()=>dispatch({type:'SET_MODE',mode:'gis'})}>Edit in GIS</button><button className="btn speed-ribbon-btn" type="button" disabled={!draft} onClick={()=>dispatch({type:'APPLY_SPEED_DRAFT'})}>Apply Draft</button><button className={`btn speed-ribbon-btn ${state.speed.history.length?'':'hidden'}`} type="button" onClick={()=>dispatch({type:'PATCH_SPEED',patch:{modal:'history'}})}>History</button></div>{state.speed.draftHealthOpen&&<aside className="speed-overlap-drawer"><div className="speed-overlap-head"><div><strong>Draft Health</strong><span>Coverage, gaps, dan geometry review.</span></div><button className="speed-modal-x" type="button" onClick={()=>dispatch({type:'PATCH_SPEED',patch:{draftHealthOpen:false}})}>×</button></div><div className="speed-overlap-list"><div className="speed-overlap-route"><div><strong>Coverage corridor</strong><small>{segments.length} polygon generated</small></div><div className="speed-overlap-route-actions"><button className="primary" type="button" onClick={()=>dispatch({type:'SET_MODE',mode:'gis'})}>Review GIS</button></div></div><div className="speed-overlap-route"><div><strong>Unreviewed segments</strong><small>{review} segment perlu Engineering review</small></div></div></div></aside>}</div>;
}

function PlaybackTelemetry() {
  const { state, dispatch, fullRows } = useWorkspace();
  if (!state.playback.active) return null;
  const unit = state.playback.focusedUnit ?? state.appliedFilters.units[0];
  const unitRows = fullRows.filter((row)=>row.unitNo===unit); const index = Math.min(unitRows.length-1,Math.max(0,Math.round((state.playback.progress/1000)*Math.max(0,unitRows.length-1)))); const sample = unitRows[index];
  return <div id="playbackTelemetry" className="playback-telemetry"><div className="playback-mode-badge"><span className="playback-live-dot"></span>PLAYBACK</div><label className="playback-focus-wrap"><span>Unit</span><select className="playback-focus-select" value={unit??''} onChange={(event)=>dispatch({type:'PATCH_PLAYBACK',patch:{focusedUnit:event.target.value}})}>{state.appliedFilters.units.map((unitNo)=><option key={unitNo}>{unitNo}</option>)}</select></label><div className="playback-telemetry-divider"></div><div className="playback-stat"><span className="playback-stat-label">Loader</span><strong>—</strong></div><div className="playback-stat"><span className="playback-stat-label">Speed</span><strong>{sample?fmt(sample.speed,1):'—'} <small>km/h</small></strong></div><div className="playback-stat playback-status-stat"><span className="playback-stat-label">PLM Status</span><strong><i id="pbStatusDot" style={{background:sample?.status===1?'#d48a47':'#22c55e'}}></i>{sample?.status===1?'PLM Loading':'Running'}</strong></div><div className="playback-stat"><span className="playback-stat-label">Waktu</span><strong>{sample?new Date(sample.time+8*3600000).toISOString().slice(11,19):'—'}</strong></div><div className="playback-stat playback-position-stat"><span className="playback-stat-label">Posisi</span><strong>{sample?`${sample.lat.toFixed(5)}, ${sample.lon.toFixed(5)}`:'—'}</strong></div>{state.mode==='duration'&&<div id="pbPitWrapV22" className="playback-stat playback-status-stat"><span className="playback-stat-label">Pit Stop</span><strong id="pbPitStateV22">{sample?'OUTSIDE':'—'}</strong></div>}</div>;
}

function PlaybackBar() {
  const { state, dispatch, fullRows } = useWorkspace();
  useEffect(()=>{
    if(!state.playback.active||!state.playback.playing)return undefined;
    let last=performance.now(); let frame;
    const tick=(now)=>{const delta=now-last;last=now;const span=fullRows.length?Math.max(...fullRows.map((r)=>r.time))-Math.min(...fullRows.map((r)=>r.time)):1;const increment=delta*state.playback.speed/span*1000;const next=Math.min(1000,state.playback.progress+increment);dispatch({type:'PATCH_PLAYBACK',patch:{progress:next,playing:next>=1000?false:true}});if(next<1000)frame=requestAnimationFrame(tick)};
    frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
  },[state.playback.active,state.playback.playing,state.playback.speed,state.playback.progress,fullRows,dispatch]);
  if(!state.playback.active)return null;
  const min=fullRows.length?Math.min(...fullRows.map((row)=>row.time)):0,max=fullRows.length?Math.max(...fullRows.map((row)=>row.time)):1,current=min+(max-min)*state.playback.progress/1000;
  return <div id="playbackBar" className="playback-bar"><div className="playback-transport"><button className="playback-btn primary" type="button" onClick={()=>dispatch({type:'PATCH_PLAYBACK',patch:{playing:!state.playback.playing}})}>{state.playback.playing?'❚❚':'▶'}</button><button className="playback-btn" type="button" onClick={()=>dispatch({type:'PATCH_PLAYBACK',patch:{playing:false,progress:0}})}>■</button></div><span className="playback-clock">{current?new Date(current+8*3600000).toISOString().slice(11,19):'--:--:--'}</span><div className="playback-timeline-wrap"><input className="playback-timeline" type="range" min="0" max="1000" value={state.playback.progress} onChange={(event)=>dispatch({type:'PATCH_PLAYBACK',patch:{progress:Number(event.target.value)}})}/></div><div className="playback-speeds">{[1,5,10,30,60,120].map((speed)=><button type="button" key={speed} className={state.playback.speed===speed?'active':''} onClick={()=>dispatch({type:'PATCH_PLAYBACK',patch:{speed}})}>{speed}×</button>)}</div><span className="playback-unit-count">{state.appliedFilters.units.length} unit</span><button className="playback-close" type="button" onClick={()=>dispatch({type:'CLOSE_PLAYBACK'})}>Tutup</button></div>;
}

function MapTools({ mapRef }) {
  const { state, dispatch, rows } = useWorkspace(); const [layerOpen,setLayerOpen]=useState(false);
  const nextTilt=()=>{const next=state.tilt===0?45:state.tilt===45?60:0;dispatch({type:'SET_TILT',value:next})};
  if(state.mode==='gis')return null;
  return <><div className="map-tools"><button className={`toolbtn ${state.mapTool==='pan'?'active':''}`} type="button" title="Pan / geser peta" onClick={()=>dispatch({type:'SET_MAP_TOOL',tool:'pan'})}>✋</button><button className={`toolbtn ${state.mapTool==='draw'?'active':''}`} type="button" title="Draw area" onClick={()=>dispatch({type:'SET_MAP_TOOL',tool:'draw'})}>◇</button><button className={`toolbtn ${state.mapTool==='measure'?'active':''}`} type="button" title="Ukur jarak" onClick={()=>dispatch({type:'SET_MAP_TOOL',tool:'measure'})}>↔</button><button className="toolbtn" type="button" title={`Tilt ${state.tilt}°`} data-pitch={`${state.tilt}°`} onClick={nextTilt}>◩</button><span className="tool-sep"></span><button className="toolbtn" type="button" title="Perbesar" onClick={()=>mapRef.current?.zoomIn()}>＋</button><button className="toolbtn" type="button" title="Perkecil" onClick={()=>mapRef.current?.zoomOut()}>−</button><button className="toolbtn" type="button" title="Fit / reset extent" onClick={()=>mapRef.current?.fitRows(rows)}>⌗</button><span className="tool-sep"></span><button className={`toolbtn ${layerOpen?'active':''}`} type="button" title="Layer" onClick={()=>setLayerOpen((value)=>!value)}>▦</button></div>{layerOpen&&<div className="popover" style={{position:'absolute',top:8,right:52,minWidth:260,left:'auto'}}><div className="pop-title" style={{marginTop:0}}>Layer Peta</div>{[['trace','Dot trace historis'],['loading','PLM Loading'],['boundary','Boundary distrik'],['roads','Jalan tambang'],['ortho','Orthophoto']].map(([key,label])=><label className="check-row" key={key}><span className="check-main"><input type="checkbox" checked={state.layers[key]} onChange={(event)=>dispatch({type:'SET_LAYER',key,value:event.target.checked})}/>{label}</span></label>)}</div>}</>;
}

function LoadingMask(){const{state}=useWorkspace();if(!state.boot.loading&&!state.boot.error)return null;return <div className="loading"><div className="card loadingbox"><div className="title">{state.boot.error?'Runtime error':'Memuat data Cycle Time'}</div><div className="sub">{state.boot.error?state.boot.text:'Membaca fixture BRCB dan layer peta.'}</div><div className="progress"><span></span></div></div></div>}

export default function MapWorkspace(){const{state}=useWorkspace();const mapRef=useRef(null);const dockHeight=state.dock.state==='collapsed'?'46px':`${state.dock.height}%`;return <section className="workspace"><article className="card map-card"><div className={`map-shell ${state.mode==='speed'?'speed-mode':''} ${state.playback.active?'playback-active':''}`} style={{'--dock-h':dockHeight}}><MapCanvas ref={mapRef}/><MapTools mapRef={mapRef}/><DurationWorkspace/><DataLogWorkspace/><div className="cycle-overlay"><CycleRibbon/><SpeedRibbon/><PlaybackTelemetry/></div><GisWorkspace mapRef={mapRef}/><div id="mapStatus" className="map-status">z13.0</div>{!['gis','datalog'].includes(state.mode)&&<><div className="context-legend" aria-label="Legenda konteks peta"><div className="leg"><span className="ctx-boundary"></span>Boundary</div><div className="leg"><span className="ctx-road"></span>Jalan Tambang</div><div className="leg"><span className="ctx-loading"></span>PLM Loading</div><div className="leg"><span className="ctx-loader"></span>Estimasi Loader Area</div></div><div className="legend"><div className="leg"><span className="sw" style={{background:'rgb(59,130,246)'}}></span> ≥30 kph</div><div className="leg"><span className="sw" style={{background:'rgb(34,197,94)'}}></span> 25–30 kph</div><div className="leg"><span className="sw" style={{background:'rgb(251,191,36)'}}></span> 20–25 kph</div><div className="leg"><span className="sw" style={{background:'rgb(139,69,19)'}}></span> 10–20 kph</div><div className="leg"><span className="sw" style={{background:'rgb(239,68,68)'}}></span> &lt;10 kph</div></div></>}<PlaybackBar/><AnalysisDock/><LoadingMask/></div></article></section>}
